### ISSUE TITLE
Incompatibility with MUI^6.1.6

### ISSUE THREAD

**Issue by MindRapist** [ZakAlbert/react-material-you-theme#9]
I installed and used it as a main wrapper for all html code inside a new project with the latest releases of MUI

`"@emotion/cache": "^11.13.1",
    "@emotion/react": "^11.13.3",
    "@emotion/styled": "^11.13.0",
    "@material/material-color-utilities": "^0.3.0",
    "@mui/icons-material": "^6.1.6",
    "@mui/material": "^6.1.6",
    "@mui/material-nextjs": "^6.1.6",
    "@mui/x-data-grid": "^7.22.2",
    "@mui/x-date-pickers": "^7.22.2",`

the result is this issue from the @mui/utils lib:
`app-router.js:52 Error: MUI: Unsupported `` color.
The following formats are supported: #nnn, #nnnnnn, rgb(), rgba(), hsl(), hsla(), color().
    at decomposeColor (colorManipulator.js:82:11)
    at alpha (colorManipulator.js:243:11)
    at eval (IconButton.js:155:255)
    at Array.map (<anonymous>)
    at eval (IconButton.js:148:14)
    at styleMemoized (memoTheme.js:27:80)
    at processStyle (createStyled.js:51:55)
    at styleFunctionProcessor (createStyled.js:162:18)
    at handleInterpolation (emotion-serialize.development.esm.js:154:24)
    at serializeStyles (emotion-serialize.development.esm.js:285:15)
    at eval (emotion-styled-base.browser.development.esm.js:209:91)
    at MuiIconButton-root (emotion-element-7a1343fa.browser.development.esm.js:71:12)
    at react-stack-bottom-frame (react-dom-client.development.js:22339:20)
    at renderWithHooks (react-dom-client.development.js:5731:22)
    at updateForwardRef (react-dom-client.development.js:7736:19)
    at beginWork (react-dom-client.development.js:9988:18)
    at runWithFiberInDEV (react-dom-client.development.js:544:16)
    at performUnitOfWork (react-dom-client.development.js:14986:22)
    at workLoopSync (react-dom-client.development.js:14816:41)
    at renderRootSync (react-dom-client.development.js:14794:11)
    at performWorkOnRoot (react-dom-client.development.js:14329:46)
    at performWorkOnRootViaSchedulerTask (react-dom-client.development.js:15843:7)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:44:48)

The above error occurred in the <Unknown> component. It was handled by the <ReactDevOverlay> error boundary.`

**Comment by Kamilake** [comment]
inverseOnPrimary are empty. Fill in their values.

![Image](https://github.com/user-attachments/assets/1571a198-b75c-4bd3-ae47-b985daf031eb)

![Image](https://github.com/user-attachments/assets/3d69b37e-4583-4c6d-8516-be5ba96eae73)
